# Generated by Django 5.0.6 on 2024-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=10)),
            ],
        ),
    ]
