# Generated by Django 5.0.6 on 2024-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestiondeCultura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatro',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
