# Generated by Django 5.0.6 on 2024-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestiondeCultura', '0002_alter_teatro_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
