# Generated by Django 5.0.6 on 2024-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestiondeCultura', '0003_danza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('genero', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
    ]
