# Generated by Django 5.0.6 on 2024-06-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestiondeCultura', '0006_rename_probado_gastronomia_testeado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cine',
            old_name='edad',
            new_name='edad_minima',
        ),
    ]
