# Generated by Django 5.0.6 on 2024-06-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestiondeCultura', '0010_cine_estreno_cine_fecha_danza_clasico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teatro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
